version: '3.1'

services:
  stats-server:
    build:
      context: ./stats-service/server
    image: stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - spring_datasource_url=jdbc:postgresql://stats-db:5432/stats-server-db
      - spring.datasource.user=root
      - spring.datasource.password=root

  stats-db:
    image: postgres:14.3-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-server-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ewm-service
    image: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-server-db

  ewm-db:
    image: postgres:14.3-alpine
    ports:
      - "6542:5433"
    environment:
      - POSTGRES_DB=ewm-server-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root